### PR TITLE
Allow geolocation field to be addable in Dexterity Type Editor

### PR DESCRIPTION
**Pull request by davilima6**
I had to monkeypatch p.a.dexterity. Would there be another way? E.g. moving that constant to registry? /cc @thet

### CODE REVIEW

**Comment by davilima6** [comment]
@jensens, why did you close this?

**Comment by thet** [comment]
@davilima6 maybe by accident or maybe because it wasn't mergable?
you might need to rebase your changes against current master, which has changed in meantime.

but anyhow - monkey patching isn't a nice thing. i really would avoid that. there must be another way... and if not, dexterity / schemaeditor has to be fixed.

**Comment by jensens** [comment]
Oh, you're PR was against @thet branch which I merged and deleted. It seems Github closes all PRs against the deleted branch then automatically. May you open a fresh one now against master?

**Comment by davilima6** [comment]
@thet, I agree. Do you see any strategy other than moving [this plone.app.dexterity constant](https://github.com/plone/plone.app.dexterity/blob/master/plone/app/dexterity/browser/types.py#L32-L50) to a key in the registry? I think no upgrade steps would be needed at this point, only some documentation to let integrators know how to extend that list - and remember to unsubscribe on uninstall. Do you see any other risks?

PR is open again with the working code: #8.

**Pull request closed without merging**
