### PR TITLE
leaflet maps integration

### PR DESCRIPTION
**Pull request by thet**
integration of leaflet maps for plone.formwidget.geolocation with edit and view mode.

### CODE REVIEW

**Comment by cewing** [comment]
@thet Thanks for this!  

@davisagli and I are working on a simple product with content types that have a single geolocation field via collective.geolocationbehavior.  I've tried installing this branch of plone.formwidget.geolocation to test it out and am noticing some odd behaviors.  

First, after installing the package the edit view for our type shows a space for the map to appear, but no map appears.  I see an error reported by the Chrome developer tools in plone-legacy-compiled.js:

    Uncaught SyntaxError: Unexpected identifier

The location of the error is the line in the file that is the minified libs.js file from this package.  

If I turn on development mode for the resource registry, and then enable debug for the Plone legacy bundle I can see the map appear.  However the initial load of the edit page throws the following error:

```
Uncaught Error: Mismatched anonymous define() module: [object Object]
  http://requirejs.org/docs/errors.html#mismatch
  makeError                                             require.js:166        
  intakeDefines                                         require.js:1229
  (anonymous function)                                  require.js:1416 
```

In addition, the search interface does not work.  It does send a request to the geocoding service, but the response from that service raises this error:
```
Uncaught Error: Couldn't autodetect 
 L.Icon.Default.imagePath, set it manually.             libs.js:3445 

 e.Icon.Default.e.Icon.extend._getIconUrl               libs.js:3350
 e.Icon.e.Class.extend._createIcon                      libs.js:3342 
 e.Icon.e.Class.extend.createIcon                       libs.js:3583 
 e.Marker.e.Class.extend._initIcon                      libs.js:3501 
 e.Marker.e.Class.extend.onAdd                          libs.js:2255 
 e.Map.e.Class.extend._layerAdd                         libs.js:1713 
 e.Map.e.Class.extend.addLayer                          libs.js:3511 
 e.Marker.e.Class.extend.addTo                          libs.js:10113 
 L.Control.GeoSearch.L.Control.extend._showLocation     libs.js:10102 
 L.Control.GeoSearch.L.Control.extend._processResults   libs.js:10066 
 e.onreadystatechange
```

Does any of this ring any bells for you?  Are we missing something in the installation process that we need to do?

**Comment by thet** [comment]
oh, you're on Plone 5 as @davisagli  was already mentioning.

well, the ``L.Icon.Default.imagePath, set it manually.`` should be fixed by Leaflet awesome icons, but i guess the compiled legacy js can't find the image resources from the plone.formwidget.geolocation resources directory. Sounds too me, that we have to rethink how legacy scripts are integrated into Plone 5.

the ``Uncaught Error: Mismatched anonymous define() module: [object Object]`` is sometimes harmless, sometimes not, IIRC. here is the error explanation: http://requirejs.org/docs/errors.html#mismatch
maybe it's a problem that Leaflet registers itself as anonymous module in require.js. Maybe we have to sed-out the anonymous define section or fork Leaflet....

It would be awesome to have a leaflet mockup pattern. i started one but gave up because of require.js incompatibilities, which i couldn't resolve back then: https://github.com/thet/mockup-leaflet

@ebrehault created a leaflet pattern in mockup-extra, which is working:
https://github.com/plone/mockup-extra
http://plone.github.io/mockup-extra/#patterns/leaflet

**Comment by thet** [comment]
@cewing can you try again, please? i sed' the resources to include the full path. might resolve the imagePath problem, but didn't test, as i'm running out  o time.

**Comment by cewing** [comment]
@thet,

That did solve a related issue where the icons for the layer selection widget and the zoom widget on the map are not appearing, but did not solve the larger issue with the imagePath not being resolvable when a response returns from the geocoding backend during location search. Nor does it cause the "mismatched define" error to go away, but I do not think that particular error is causing any problems.

Also, unless I put the resource registry into development mode and turn on "debug javascript" for the legacy bundle, the map is not visible at all in either display or edit mode, though a space is reserved in the DOM where it should be showing.  I still get the same error in that case:

    Uncaught SyntaxError: Unexpected identifier

I suspect that a pattern to support this is the right way to go.  Something in the handling of the javascript from the registry for the legacy bundle is just not working well.  I wish I could offer better debugging information.  Thanks for the quick response.

**Comment by thet** [comment]
first, the reported issues only arise in Plone 5. in Plone 4 everything works quite well.

i register now an unminified version of libs.js, which makes the map visible in plone 5. looks like, requirejs cannot deal very well with already minified code.

i can confirm the issue with imagePath.

another issue is, that bootstrap's font-awesome isn't available. this is why a © is rendered on the marker instead of a home symbol.

using a mockup pattern would be the best, i guess.

**Comment by thet** [comment]
@davisagli @cewing what's your plan on this issue?
can we merge this pull-request, even it's not working in plone 5?
did you try out any mockup options?

there is still the option of using the branch, where P.Maps was in. If that works out great, i'm sure there are options of bringing P.Maps back in, although i'd not recommend it.

by the way, font-awesome shouldn't be necessary. it "should" work with glyphicons too.

**Pull request merged**
