### PR TITLE
Add `default_input_zoom` and `default_display_zoom` options in control panel

### PR DESCRIPTION
**Pull request by laulaz**
Cherry-picked / adapted from https://github.com/IMIO/plone.formwidget.geolocation/commits/fix-geosearch

cc @mpeeters

### CODE REVIEW

**Review by yurj — COMMENTED** [review]
Hi! the pull misses a registry.xml in the profile

**Comment by laulaz** [comment]
> Hi! the pull misses a registry.xml in the profile

The upgrade step (re)plays the existing `registry.xml` (to add the 2 new fields) 😉

**Comment by mpeeters** [comment]
The fields are defined in an interface referenced in https://github.com/collective/plone.formwidget.geolocation/blob/master/plone/formwidget/geolocation/profiles/default/registry.xml#L3.

**Comment by mpeeters** [comment]
LGTM

**Comment by laulaz** [comment]
@petschki I changed the code to add an upgrade step specifically for the new fields.
Could you please re-review ?  🙏

**Review by petschki — APPROVED** [review]
Nice!

**Pull request merged**
