### PR TITLE
Add maps configuration view

### PR DESCRIPTION
**Pull request by bsuttor**
Add view to get default lat and lon when you add a new object with geolocation behaviour.
It changes nothing if you add maps_configuration view on specific object and if object is already geolocalized.

### CODE REVIEW

**Comment by bsuttor** [comment]
I added this view because of that lines:
https://github.com/collective/plone.formwidget.geolocation/blob/master/plone/formwidget/geolocation/widget.py#L116-L117

But I just change how get map_configuration on `def _default_loc` in this [commit](https://github.com/collective/plone.formwidget.geolocation/pull/19/commits/506ea2eba8a20fbf2c0103ebe6113805f3e27a7b)

**Comment by bsuttor** [comment]
@thet Thanks,
I will update my changlog entry to match with changes.
Can I do that directly on master ?

**Comment by bsuttor** [comment]
it seems there some issues with this PR, I'm on it

**Comment by thet** [comment]
@bsuttor cool, thanks. For trivial changes or fixing broken things, do it on master.

**Comment by bsuttor** [comment]
I would like to use GeolocationField on controlpanel to choose default location instead of two fields `default_latitude` and `default_longitude`.
But GeolocationField extend a zope Object schema and that schema is not in the limited set of fields for registry.
What can I do ?

I don't make a issue or a new PR at this moment, because it related to "setting a default location".

Best regards,

**Pull request merged**
