### PR TITLE
Bundles switch while upgrading from 2.2.X to 3.0.X

### PR DESCRIPTION
**Pull request by yurj**
Upgrading removes the patternslib bundle but does not add the new bundle.

### CODE REVIEW

**Comment by yurj** [comment]
Works on a local instance. But this:
```xml
  <records interface="Products.CMFPlone.interfaces.IBundleRegistry"
           prefix="plone.bundles/bundle-leaflet"
           remove="true"
  />
```
doesn't remove the patternslib leaflet bundle. It is Plone 6.0.0a2, so maybe there are some leftovers but the registry entry is prefix plone.bundles/bundle-leaflet and interface IBundleRegistry. Oh, I found out. In Plone 6.0.0a2 the interface is `Products.CMFPlone.interfaces.resources.IBundleRegistry`. It is correct and consinstent with Plone 5.2-latest:

https://github.com/plone/Products.CMFPlone/blob/5.2.x/Products/CMFPlone/interfaces/resources.py

```python
class IResourceRegistry(zope.interface.Interface):
```

So I think we should change `Products.CMFPlone.interfaces.IBundleRegistry` to `Products.CMFPlone.interfaces.resources.IBundleRegistry` too.

@petschki @laulaz do you agree?

**Comment by laulaz** [comment]
@yurj as the 3.0.x versions are not compatible with Plone 5 anymore, shouldn't we use the "non-deprecated" `plone.base.interfaces.IBundleRegistry` interface for the bundle registration ?

**Comment by yurj** [comment]
> @yurj as the 3.0.x versions are not compatible with Plone 5 anymore, shouldn't we use the "non-deprecated" `plone.base.interfaces.IBundleRegistry` interface for the bundle registration ?

I've used what appears on the menu dropdown in the configuration registry under "IBundleRegistry", I think this interface path is well supported until Plone 7.0. This can help also to migrate from and in old Plone instances? I'm not an expert so i rise my hands on this.

**Comment by petschki** [comment]
Is this still needed? a lot has changed since 6.0a and I'm not able to reproduce this scenario ... though the interface should be changed to `plone.base` indeed. I'll create a separate PR for that.

**Comment by yurj** [comment]
If not reproducible, it is better to close this PR.

**Pull request closed without merging**
